commit1
tatavild/ImageFeed pull request #4
Opened 2023-10-10 13:42 UTC by tatavild

2023-11-07 17:11 UTC, protos17 requested changes

2023-11-07 17:11 UTC, protos17 commented on ImageFeed/Networking/OAuth2Service.swift
> +
Здесь необходимо добавить обработку повторного вызова с новым code:

       if task != nil {
            task?.cancel()
            task = nil
        }

при наличии task, отменяем его и запускаем новый task

2023-11-07 17:11 UTC, protos17 commented on ImageFeed/SplashViewController/SplashViewController.swift
> +        view.backgroundColor = UIColor(named: "YP black")
У тебя в ассетах цвет написан с большой буквы, а здесь ты пишешь с маленькой. Чтобы это исправить, необходимо заменить на:

      view.backgroundColor = UIColor(named: "YP Black")

рекомендую вынести в extension и вызывать через точку:

       extension UIColor {
           static let ypBlack = UIColor(named: "YP Black")
      }

2023-11-07 17:11 UTC, protos17 commented on ImageFeed/ImageList/ImageListViewController.swift
>      private let ShowSingleImageSegueIdentifier = "ShowSingleImage"
Константы принято писать с маленькой буквы

2023-11-07 17:11 UTC, protos17 commented on ImageFeed/Profile/ProfileImageService.swift
> +    static let didChangeNotification = Notification.Name(rawValue: "ProfileImageProviderDidChange")
Рекомендую перенести в extension и вызывать его через точку:

      extension Notification.Name {
          static let didChangeNotification = Notification.Name("ProfileImageProviderDidChange")
      }

2023-11-07 17:11 UTC, protos17 commented on ImageFeed/Profile/ProfileImageService.swift
> +        urlComponents.host = "api.unsplash.com"
Рекомендую перенести в Constants

2023-11-07 17:11 UTC, protos17 commented on ImageFeed/Profile/ProfileService.swift
> +        self.fetchProfile(token) { result in
Сильная ссылка, необходимо добавить weak self

2023-11-07 17:11 UTC, protos17 commented on ImageFeed/Profile/ProfileService.swift
> +                fatalError("Error: \(error)")
Хочу отметить, что в продакшене не используется fatalError, кроме случаев, когда это необходимо, например, в банковском приложении при обнаружении джейлбрейка. Лучше заменить на break или показать алерт с ошибкой пользователю

2023-11-07 17:11 UTC, protos17 commented on ImageFeed/Profile/ProfileService.swift
> +        urlComponents.host = "api.unsplash.com"
Рекомендую тоже перенести в Constants

2023-11-07 17:11 UTC, protos17 commented on ImageFeed/Profile/ProfileService.swift
> +            fatalError("Failed to create URL")
Рекомендую заменить на return

2023-11-07 17:11 UTC, protos17 commented on ImageFeed/SingleImageView/SingleImageViewController.swift
> +    var image: UIImage! {
Рекомендую аккуратнее работать с опционалами и не использовать принудительное извлечение. Здесь лучше оставить его опциональным и добавить проверку, что картинка присутствует

2023-11-07 17:11 UTC, protos17 commented on ImageFeed/SingleImageView/SingleImageViewController.swift
> +            activityItems: [image!],
Здесь тоже не рекомендую использовать принудительное извлечение опционалов

2023-11-07 17:11 UTC, protos17 commented on ImageFeed/SplashViewController/SplashViewController.swift
> +            fatalError("Invalid AuthViewController Configuration")}
Рекомендую заменить на return

2023-11-07 17:11 UTC, protos17 commented on ImageFeed/SplashViewController/SplashViewController.swift
> +                UIBlockingProgressHUD.dismiss()
UIBlockingProgressHUD.dismiss() дублируется, рекомендую вынести в общую область видимости

2023-11-07 17:11 UTC, protos17 commented on ImageFeed/SplashViewController/SplashViewController.swift
> +                UIBlockingProgressHUD.dismiss()
UIBlockingProgressHUD.dismiss() рекомендую также вынести в общую область видимости

2023-11-07 17:11 UTC, protos17 commented on ImageFeed/SplashViewController/SplashViewController.swift
> +                self?.switchToTabBarController()
Чтобы гарантировано у нас была картинка профиля, рекомендую переход на таб бар сделать в замыкании:

      self?.profileImageService.fetchProfileImageURL(username: username.username) { _ in
                    DispatchQueue.main.async {
                        self?.switchToTabBarController()
                    }
                }

2023-11-07 17:11 UTC, protos17 commented on ImageFeed/SplashViewController/SplashViewController.swift
> +        let okAction = UIAlertAction(title: "Oк", style: .default, handler: { _ in })
Рекомендую в аргументах функции передавать действие (заново отправлять запрос) и сюда его передать в handler

2023-11-07 17:11 UTC, protos17 commented on ImageFeed/URLRequestExtension.swift
> +            let url = URL(string: "https://unsplash.com"),
Рекомендую перенести в Constants

2023-11-07 17:11 UTC, protos17 commented on ImageFeed/Constants.swift
> +let tokenKey = "ImageFeedOAuth2Token"
Рекомендую вынести в энам и обращаться через static let

2023-11-12 13:50 UTC, protos17 approved these changes

2023-11-12 13:50 UTC, protos17 commented on ImageFeed/AlertPresenter.swift
> +import Foundation
При импорте UIKit можно не импортировать Foundation, потому что первый содержит в себе второй

2023-11-12 13:50 UTC, protos17 commented on ImageFeed/Auth/AuthViewController.swift
> +    private let ShowWebViewSegueIdentifier = "ShowWebView"
Константы принято писать с маленькой буквы

2023-11-12 13:50 UTC, protos17 commented on ImageFeed/Profile/ProfileViewController.swift
> +class ProfileViewController: UIViewController {
Класс без наследования, рекомендую указать как final

2023-11-12 13:50 UTC, protos17 commented on ImageFeed/Profile/UserResult.swift
> +import Foundation
При импорте UIKit можно не импортировать Foundation, потому что первый содержит в себе второй

2023-11-12 13:50 UTC, protos17 commented on ImageFeed/SingleImageView/SingleImageViewController.swift
> +    @IBAction func didTapShareButton(_ sender: UIButton) {
Здесь стоит добавить `private`
Необходимо указывать private  для того, чтобы спрятать детали реализации конкретной части функциональности, когда они используются только внутри области объявления.

2023-11-12 13:50 UTC, protos17 commented on ImageFeed/SplashViewController/SplashViewController.swift
> -    }
Хорошо же было сверстано через snapKit, почему перестала использовать?

2023-11-12 13:53 UTC, tatavild commented on ImageFeed/SplashViewController/SplashViewController.swift
> -    }
Учту, спасибо Вам за все!

2023-11-12 14:06 UTC, merged